/* compiler.js -- turns the current graph into a real scripts/OnKey/*.lua file.
 *
 * Two passes, deliberately in this order:
 *   1. Every pure-data node (has onExecute, no ACTION input -- e.g. Random Number) runs once, populating
 *      its output via setOutputData. These never depend on each other in this draft, so a single flat
 *      pass is enough; a graph with data-node-to-data-node chains would need a real topological sort here
 *      instead (out of scope for this draft -- see README's "what's deliberately not done yet").
 *   2. Every trigger node (isTriggerNode === true, e.g. On Key Press) fires once via its own fireOnce(),
 *      which synchronously walks the whole onAction -> triggerSlot -> onAction chain via litegraph's own
 *      event-propagation machinery -- this compiler doesn't re-implement graph traversal, it just kicks
 *      litegraph's real one off once per trigger and lets CodeGen collect whatever each node emits.
 *
 * This only targets an OnKey script export in this draft -- see README for why OnLoad/HTML-button targets
 * are noted as the natural next step rather than built here.
 */
window.Compiler = (function () {
  function isDataNode(node) {
    return typeof node.onExecute === "function" && !node.inputs?.some(function (i) { return i.type === LiteGraph.ACTION; });
  }

  function compile(graph, opts) {
    opts = opts || {};
    CodeGen.reset();

    graph._nodes.forEach(function (node) {
      if (isDataNode(node)) node.onExecute();
    });

    var triggers = graph._nodes.filter(function (node) { return node.constructor.isTriggerNode; });
    triggers.forEach(function (node) { node.fireOnce(); });

    var body = CodeGen.getLines();
    var key = (triggers[0] && triggers[0].properties && triggers[0].properties.key) || "insert";
    var name = opts.scriptName || "GraphOutput";

    var out = [];
    out.push('local KEYVAL = "' + key + '"  -- must be in the first 10 lines');
    out.push("");
    out.push("-- " + name + ".lua -- generated by mercs2-ess-visual. Edit the graph, not this file, and re-export.");
    out.push('if not _G.Ess then Loader.Printf("' + name + ': load Ess first (1_Ess.lua in scripts/OnLoad)") return end');
    out.push("");
    body.forEach(function (line) { out.push(line); });
    out.push("");
    out.push('Ess.Log("[' + name + '] ran")');
    out.push("");

    return {
      triggerCount: triggers.length,
      lineCount: body.length,
      code: out.join("\n")
    };
  }

  return { compile: compile };
})();
